name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Inject environment variables
        run: |
          echo "VITE_GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env
          echo "VITE_API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env
          echo "VITE_NOROFF_API_KEY=${{ secrets.NOROFF_API_KEY }}" >> .env
          echo "VITE_GOOGLE_MAP_ID=${{ secrets.GOOGLE_MAP_ID }}" >> .env

      - name: Verify environment variables
        run: cat .env

      - name: Build the project
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
